# Errata — *Wine Production Forecasting Using Rule-Based Machine Learning*

**Hugo Filipe Queiróz Nogueira** · MECD, FEUP · June 2026
Corrections identified after submission of the version deposited for defense. Page numbers refer to the submitted PDF (*Tese Hugo Nogueira — final version*). All corrections are incorporated in the definitive version.

| # | Page | Location | Submitted text | Correction |
|---|------|----------|----------------|------------|
| 1 | 36 | Ch.3, §"CarenR: Distribution Rules via the CAREN Framework" | "CarenR is built on the CAREN association rule engine, **originally developed by Jorge et al. (2006)**" | The CAREN engine was developed by **Azevedo (2003)**; Jorge, Azevedo & Pereira (2006) introduced the **distribution-rule** framework on top of it. Corrected to: "…originally developed by Azevedo (2003) and extended to the discovery of distribution rules in numeric data by Jorge et al. (2006)." New reference added: Azevedo, P. J. (2003), *CAREN — A Java based Apriori implementation for classification purposes*, Tech. Report, U. Minho. |
| 2 | 99 | Bibliography, Jorge et al. (2006) | DOI `10.1007/11871637_**25**` | Correct DOI is `10.1007/11871637_**26**` (PKDD 2006, LNCS/LNAI vol. 4213, pp. 247–258, Springer). Volume and pages added. |
| 3 | 28 / 36–38 | Ch.2 (p.28) and Ch.3 Step 3 (p.36) | Search described as **"beam search"** (Ch.2) and **"breadth-first … most promising single conditions"** (Ch.3) | CAREN performs an **Apriori-style levelwise search pruned by minimum support** (exhaustive over the support-frequent region, not a heuristic beam). Both passages harmonised to this description. |
| 4 | 28, 36, 38, 49, 100+ (Appx A/B) | Minimum support threshold | Stated as **"15%"** / "≥ 15% of observations" in Ch.2, Ch.3 (Step 5 and weighting paragraph), Appendix A and Appendix B | Actual value used in the pipeline is **20%** (`carenr_min_sup <- 0.20` in `3_carenR__application.R` and `6_scenario_validation.R`), consistent with the results in Ch.4–6. All statements corrected to 20%. Derived counts corrected accordingly ("≈18 years out of 89"; weighting example "≈1.4×"). *This propagates a correction already logged in Appendix E to the chapters where it had been missed.* |
| 5 | 100 | Bibliography, Moreira et al. (2022) | Title given as "**Contrast Association Rules for Extraordinary Nodes**", plus a printed "TODO: confirm…" note | Backronym removed (title corrected to a neutral description of the R package). Printed "TODO" notes removed from this and the Fraga (2024) and Lopes (2024) entries. *Exact bibliographic metadata for Moreira (2022), Fraga (2024) and Lopes (2024) to be confirmed with supervisors.* |

**Note on nature of corrections.** All six items are editorial/bibliographic. None affects any result, table, figure, statistical test, or conclusion. The support-threshold value used in all computations was 20% throughout; item 4 corrects descriptive text that lagged the code, not the analysis itself.
