// Figures document — 4 key plots embedded with captions
const {
  Document, Packer, Paragraph, TextRun, ImageRun,
  HeadingLevel, AlignmentType, PageNumber, Footer
} = require('docx');
const fs = require('fs');

const H1 = t => new Paragraph({ heading: HeadingLevel.HEADING_1, spacing: { before: 360, after: 180 },
  children: [new TextRun({ text: t, font: 'Times New Roman', size: 28, bold: true })] });
const H2 = t => new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 300, after: 120 },
  children: [new TextRun({ text: t, font: 'Times New Roman', size: 24, bold: true })] });
const H3 = t => new Paragraph({ heading: HeadingLevel.HEADING_3, spacing: { before: 240, after: 120 },
  children: [new TextRun({ text: t, font: 'Times New Roman', size: 24, italics: true })] });
const B = t => new Paragraph({ spacing: { before: 120, after: 120, line: 360 }, alignment: AlignmentType.JUSTIFIED,
  children: [new TextRun({ text: t, font: 'Times New Roman', size: 24 })] });
const SP = () => new Paragraph({ children: [new TextRun('')], spacing: { before: 60, after: 60 } });
const CAP = t => new Paragraph({ spacing: { before: 80, after: 240 }, alignment: AlignmentType.CENTER,
  children: [new TextRun({ text: t, font: 'Times New Roman', size: 20, italics: true })] });

const PLOT_DIR = '/sessions/charming-modest-galileo/mnt/Thesis/data/linear/';

// Width in EMU: 1 inch = 914400 EMU. Page content ~15 cm = ~5.9 inches = 5,394,960 EMU
const FULL_W  = 5394960;  // ~15 cm
const FULL_H_16x9 = 3034665; // 16:9 ratio
const FULL_H_4x3  = 4046220; // 4:3 ratio

function imgPara(fname, w, h) {
  const data = fs.readFileSync(PLOT_DIR + fname);
  return new Paragraph({
    spacing: { before: 120, after: 80 },
    alignment: AlignmentType.CENTER,
    children: [new ImageRun({
      type: 'png',
      data,
      transformation: { width: Math.round(w / 9144), height: Math.round(h / 9144) },
      altText: { title: fname, description: fname, name: fname }
    })]
  });
}

// EMU to points helper (for sizing)
// 9144 EMU = 1 pt
// 914400 EMU = 100pt = 1 inch
// Target: ~14cm wide = 14/2.54 inches = ~5.5 inches = 5,029,200 EMU
// Sizes in pixels, render at 96dpi target:
// 1500x900 → render as 600x360 pts → in EMU: 600*9144=5,486,400 x 360*9144=3,291,840
// But we want ~14cm = 397pt wide

// Let's just use pixel dimensions and scale to ~500pt wide
// 500pt = 500*9144 EMU = 4,572,000 EMU wide

const W500 = 4572000;   // 500pt = ~17.6cm — fits inside A4 content area

// Aspect ratios:
// 1500x900 → 1.667 → H = W500/1.667 = 2,742,857
// 1650x825 → 2.0   → H = W500/2.0   = 2,286,000
// 1800x1200 → 1.5  → H = W500/1.5   = 3,048,000
// 1650x1050 → 1.571 → H = W500/1.571 = 2,908,978

const H_16x10  = Math.round(W500 / 1.667);  // 1500x900
const H_2x1    = Math.round(W500 / 2.0);    // 1650x825
const H_3x2    = Math.round(W500 / 1.5);    // 1800x1200
const H_detrend = Math.round(W500 / 1.571); // 1650x1050

function img(fname, aspectRatio) {
  const data = fs.readFileSync(PLOT_DIR + fname);
  const h = Math.round(W500 / aspectRatio);
  return new Paragraph({
    spacing: { before: 200, after: 80 },
    alignment: AlignmentType.CENTER,
    children: [new ImageRun({
      type: 'png',
      data,
      transformation: { width: Math.round(W500 / 9144), height: Math.round(h / 9144) },
      altText: { title: fname, description: fname, name: fname }
    })]
  });
}

const children = [
  H1('Figures'),
  SP(),
  B('This section contains the key figures referenced in the results chapters. All figures were generated by the automated R pipeline (plot_model_comparison.R) from the walk-forward evaluation results.'),
  SP(),

  // ── Figure 1: RVV time series context ──────────────────────────────────────
  H2('Figure 1 — Vinho Verde Production Time Series with Prediction Error Bands'),
  SP(),
  B('Figure 1 illustrates the full RVV production time series (1942–2021) alongside the MAE error bands for the best-performing models. The dashed horizontal line is the global mean (1,621 mhl). The shaded band centred on the mean represents the ±140 mhl error band of the Naive_Median baseline; the wider band shows the ±172 mhl error of the best CarenR variant. The figure contextualises what the MAE numbers mean in practice: even the best model has an error band that spans a substantial fraction of the series range. The structural decline from the 1960s peak (~3,000 mhl) to the modern era (~800 mhl) is clearly visible, illustrating the non-stationarity that motivates the detrending step described in Section 3.3.'),
  SP(),
  img('plot_context_timeseries.png', 1800/750),
  CAP('Figure 1. RVV annual wine production (1942–2021). Dashed line = global mean (1,621 mhl). Shaded bands = ±MAE for Naive_Median (dark, ±140 mhl) and best CarenR variant (light, ±172 mhl). The structural decline post-1980 reflects EU accession and industry restructuring, not climate variation.'),
  SP(),

  // ── Figure 2: RVV model comparison bar chart ───────────────────────────────
  H2('Figure 2 — Weighted MAE: All 17 Models, Vinho Verde'),
  SP(),
  B('Figure 2 shows the complete 17-model ranking for the Vinho Verde region, sorted by weighted MAE. The dashed vertical blue line marks the Naive_Median baseline (140 mhl). All CarenR variants (green bars) exceed this baseline, as do all other ML models. The figure visually confirms that no rule-based model consistently beats the naive baseline in RVV, and shows the substantial gap between CarenR variants (172–275 mhl) and the most poorly-performing models (RIPPER 508 mhl, Decision Tree 479 mhl). The best CarenR variant (Sup+Thresh, marked with ★) ties with CarenR_Conf at 172 mhl — the closest any ML model comes to the baseline.'),
  SP(),
  img('plot_comparison_weighted_mae.png', 1500/900),
  CAP('Figure 2. Weighted MAE for all 17 models in Vinho Verde (16 walk-forward scenarios). Blue = naive baselines; green = CarenR variants; grey = other ML models. Dashed line = Naive_Median reference (140 mhl). Lower is better.'),
  SP(),

  // ── Figure 3: Per-scenario RVV trajectory ──────────────────────────────────
  H2('Figure 3 — Per-Scenario MAE Trajectory, Vinho Verde'),
  SP(),
  B('Figure 3 shows the per-scenario MAE for key models across all 16 RVV scenarios. The Naive_Median (solid dark blue) provides a varying baseline — its per-scenario MAE reflects the inherent year-to-year production variability of each test year. The best CarenR variant (CarenR Sup+Thresh, dark green solid line) tracks close to the Naive_Median in early scenarios (1–3) then diverges progressively in scenarios 4–11, reaching a gap of ~82 mhl in Scenario 11. In the final scenarios (12–16) the gap closes because CarenR falls back to the median (no rules fire). Decision Tree (dotted grey) and M5Rules (dotted dark) are consistently and substantially above all other models. This figure directly illustrates the harmful-rules degradation pattern described in Section 5.3.'),
  SP(),
  img('plot_comparison_per_scenario.png', 1650/825),
  CAP('Figure 3. Per-scenario MAE for key models across 16 RVV walk-forward scenarios. Scenarios are ordered chronologically; earlier scenarios have larger test sets. CarenR Sup+Thresh (dark green) tracks the baseline in early/late scenarios but diverges in scenarios 4–11 when harmful rules fire.'),
  SP(),

  // ── Figure 4: Detrend comparison ────────────────────────────────────────────
  H2('Figure 4 — Linear vs LOESS Detrending: Weighted MAE Comparison'),
  SP(),
  B('Figure 4 compares the weighted MAE for all 17 models under linear detrending (blue bars) versus LOESS detrending (green bars) for the Vinho Verde region. The two vertical dashed lines show the respective Naive_Median baselines: green (LOESS, ~90 mhl) and blue (linear, ~140 mhl). For every model, LOESS detrending produces a lower absolute MAE — the green bars are consistently shorter than the blue bars. This reflects the better trend fit of LOESS for RVV (Decision 1 improvement). However, CarenR_Lag under LOESS (green bar, short) is notable: even with a lower baseline, CarenR falls to or below the baseline with LOESS because rules are suppressed. The figure visually demonstrates the Decision 1 / Decision 2 trade-off: LOESS moves the goalposts (lower floor) but prevents CarenR from scoring at all.'),
  SP(),
  img('plot_detrend_comparison.png', 1650/1050),
  CAP('Figure 4. Weighted MAE under linear (blue) vs LOESS (green) detrending for all 17 models, Vinho Verde. Dashed lines = Naive_Median baseline for each detrend method (linear: 140 mhl, LOESS: ~90 mhl). LOESS improves Decision 1 (lower floor) but suppresses CarenR rule induction, illustrating the fundamental trade-off between trend quality and residual signal availability.'),
  SP(),
];

const doc = new Document({
  styles: { default: { document: { run: { font: 'Times New Roman', size: 24 } } },
    paragraphStyles: [
      { id: 'Heading1', name: 'Heading 1', basedOn: 'Normal', next: 'Normal', quickFormat: true,
        run: { size: 28, bold: true, font: 'Times New Roman' }, paragraph: { spacing: { before: 360, after: 180 }, outlineLevel: 0 } },
      { id: 'Heading2', name: 'Heading 2', basedOn: 'Normal', next: 'Normal', quickFormat: true,
        run: { size: 24, bold: true, font: 'Times New Roman' }, paragraph: { spacing: { before: 300, after: 120 }, outlineLevel: 1 } },
      { id: 'Heading3', name: 'Heading 3', basedOn: 'Normal', next: 'Normal', quickFormat: true,
        run: { size: 24, italics: true, font: 'Times New Roman' }, paragraph: { spacing: { before: 240, after: 120 }, outlineLevel: 2 } },
    ] },
  sections: [{ properties: { page: { size: { width: 11906, height: 16838 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1800 } } },
    footers: { default: new Footer({ children: [new Paragraph({ alignment: AlignmentType.CENTER,
      children: [new TextRun({ children: [PageNumber.CURRENT], font: 'Times New Roman', size: 20 })] })] }) },
    children }]
});

Packer.toBuffer(doc).then(buf => {
  fs.writeFileSync('/sessions/charming-modest-galileo/mnt/outputs/figures.docx', buf);
  const sizeKB = Math.round(buf.length / 1024);
  console.log(`Done: figures.docx (${sizeKB} KB)`);
});
