---
title: "Inspect dist rules datasets"
output: html_notebook
---

```{r}
library(tidyverse)


```



```{r}

df_rdd <- read.csv(file = '../../data/dataPrep_dis_rule_dataset_rdd.csv') %>% 
  mutate(region = 'rdd')


df_rvv <- read.csv(file = '../../data/dataPrep_dis_rule_dataset_rvv.csv') %>% 
  mutate(region = 'rvv')

df <- rbind(df_rdd,df_rvv)

glimpse(df)

head(df)



for (col in names(df)) {
  if (col == 'Wine_mhl') {
    df[[col]] = as.numeric(df[[col]])
  } else{
    df[[col]] = as.factor(df[[col]])
  }
  cat(col,'---',class(df[[col]]),'\n')
}

```

# Wine production distribution

```{r}


# Create a histogram using ggplot
df %>% 
  ggplot(aes(x = Wine_mhl, fill = region)) +
  geom_density( position = "identity", alpha = 0.5) +
  labs(title = "Histogram for the Wine_mhl", subtitle = 'RVV and RDD region',
       x = "Wine_mhl Values", y = "Frequency") +
  scale_fill_manual(values = c("blue", "red")) +
  theme_minimal() +
  theme(legend.position = "top")


```

```{r}



# Loop through each column and create a bar plot

for (col in names(df)) {
  plot_data <- data.frame(Value = df[[col]], region = df$region)
  
  p <- ggplot(plot_data, aes(x = Value, fill = region)) +
    geom_bar() +
    labs(title = paste("Bar Plot for", col),
         x = col, y = "Count") +
    theme_minimal() +
    facet_wrap(~region) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
  
  print(p)
}








```

